### ISSUE TITLE
Image hyperlinks broke

### ISSUE THREAD

**Issue by thegilpatrick** [jwilber/USDA_Pomological_Watercolors#1]
Hey, 
really enjoy your work on https://mlu-explain.github.io/. 

I was about to play around with this dataset and found the image hyperlinks were broken. So I fixed the hyperlinks. Thanks for this dataset!

[fruit.csv](https://github.com/jwilber/USDA_Pomological_Watercolors/files/11761296/fruit.csv)

**Comment by jwilber** [comment]
Ty!
And thanks for the update csv!
